import { defineConfig } from "vitepress";

// https://vitepress.dev/reference/site-config
export default defineConfig({
  lang: "zh-CN",
  title: "Anqing's blog",
  description: "Anqing's blog website, generated by VitePress.",
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: "主页", link: "/" },
      { text: "文章", link: "/posts/index" },
      { text: "镜像文档", link: "/posts/index" },
      { text: "Demos", link: "/demos/index" },
    ],
    socialLinks: [{ icon: "github", link: "https://github.com/Anqing-None" }],
  },
});
